//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

using System;

namespace Корректор_ФЭС.XSD
{
    using System.Data;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class СообщОперКО
    {
        [NonSerialized] public DataTable tableОперации; // это не штатное поле

        private СлужЧастьТип служЧастьField;

        private СообщОперКОИнформЧасть информЧастьField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СлужЧастьТип СлужЧасть
        {
            get
            {
                return this.служЧастьField;
            }
            set
            {
                this.служЧастьField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧасть ИнформЧасть
        {
            get
            {
                return this.информЧастьField;
            }
            set
            {
                this.информЧастьField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СлужЧастьТип
    {

        private СлужЧастьТипВерсияФормата версияФорматаField;

        private string версПрогField;

        private string иДКоррField;

        private string типИнфField;

        private string датаСообщенияField;

        private string уполнСотруднField;

        private ФИО фИОУполнСотруднField;

        private string телУполнСотруднField;

        private string электроннаяПочтаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СлужЧастьТипВерсияФормата ВерсияФормата
        {
            get
            {
                return this.версияФорматаField;
            }
            set
            {
                this.версияФорматаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИДКорр
        {
            get
            {
                return this.иДКоррField;
            }
            set
            {
                this.иДКоррField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТипИнф
        {
            get
            {
                return this.типИнфField;
            }
            set
            {
                this.типИнфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаСообщения
        {
            get
            {
                return this.датаСообщенияField;
            }
            set
            {
                this.датаСообщенияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string УполнСотрудн
        {
            get
            {
                return this.уполнСотруднField;
            }
            set
            {
                this.уполнСотруднField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФИО ФИОУполнСотрудн
        {
            get
            {
                return this.фИОУполнСотруднField;
            }
            set
            {
                this.фИОУполнСотруднField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТелУполнСотрудн
        {
            get
            {
                return this.телУполнСотруднField;
            }
            set
            {
                this.телУполнСотруднField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ЭлектроннаяПочта
        {
            get
            {
                return this.электроннаяПочтаField;
            }
            set
            {
                this.электроннаяПочтаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum СлужЧастьТипВерсияФормата
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.0")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИО
    {

        private string фамField;

        private string имяField;

        private string отчField;

        private string фИОСтрокаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Фам
        {
            get
            {
                return this.фамField;
            }
            set
            {
                this.фамField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Отч
        {
            get
            {
                return this.отчField;
            }
            set
            {
                this.отчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ФИОСтрока
        {
            get
            {
                return this.фИОСтрокаField;
            }
            set
            {
                this.фИОСтрокаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class МестоПриемаВыдача
    {

        private string идТерминалField;

        private Адрес адрМестаПриемаВыдачаField;

        private string бИККОField;

        private string наимКОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИдТерминал
        {
            get
            {
                return this.идТерминалField;
            }
            set
            {
                this.идТерминалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес АдрМестаПриемаВыдача
        {
            get
            {
                return this.адрМестаПриемаВыдачаField;
            }
            set
            {
                this.адрМестаПриемаВыдачаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БИККО
        {
            get
            {
                return this.бИККОField;
            }
            set
            {
                this.бИККОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимКО
        {
            get
            {
                return this.наимКОField;
            }
            set
            {
                this.наимКОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Адрес
    {

        private string индексField;

        private string кодОКСМField;

        private string странаНаименованиеField;

        private string кодСубъектаПоОКАТОField;

        private string районField;

        private string пунктField;

        private string улицаField;

        private string домField;

        private string корпField;

        private string офField;

        private string адресСтрокаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодОКСМ
        {
            get
            {
                return this.кодОКСМField;
            }
            set
            {
                this.кодОКСМField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СтранаНаименование
        {
            get
            {
                return this.странаНаименованиеField;
            }
            set
            {
                this.странаНаименованиеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодСубъектаПоОКАТО
        {
            get
            {
                return this.кодСубъектаПоОКАТОField;
            }
            set
            {
                this.кодСубъектаПоОКАТОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Пункт
        {
            get
            {
                return this.пунктField;
            }
            set
            {
                this.пунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Корп
        {
            get
            {
                return this.корпField;
            }
            set
            {
                this.корпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Оф
        {
            get
            {
                return this.офField;
            }
            set
            {
                this.офField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string АдресСтрока
        {
            get
            {
                return this.адресСтрокаField;
            }
            set
            {
                this.адресСтрокаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class БанкПлательщикПолучатель
    {

        private string бИККОField;

        private string наимКОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БИККО
        {
            get
            {
                return this.бИККОField;
            }
            set
            {
                this.бИККОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимКО
        {
            get
            {
                return this.наимКОField;
            }
            set
            {
                this.наимКОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ИдентификаторИНБОЮЛ
    {

        private string номерИНБОЮЛField;

        private string кодИНБОЮЛField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерИНБОЮЛ
        {
            get
            {
                return this.номерИНБОЮЛField;
            }
            set
            {
                this.номерИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодИНБОЮЛ
        {
            get
            {
                return this.кодИНБОЮЛField;
            }
            set
            {
                this.кодИНБОЮЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СведенияИНБОЮЛ
    {

        private string полноеНаимИНБОЮЛField;

        private string наимИНБОЮЛField;

        private ИдентификаторИНБОЮЛ[] регИНБОЮЛField;

        private Адрес местоДеятельностьИНБОЮЛField;

        private string признакОргФормаИНБОЮЛField;

        private СведенияИНБОЮЛУчредитель[] учредительField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПолноеНаимИНБОЮЛ
        {
            get
            {
                return this.полноеНаимИНБОЮЛField;
            }
            set
            {
                this.полноеНаимИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимИНБОЮЛ
        {
            get
            {
                return this.наимИНБОЮЛField;
            }
            set
            {
                this.наимИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("РегИНБОЮЛ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ИдентификаторИНБОЮЛ[] РегИНБОЮЛ
        {
            get
            {
                return this.регИНБОЮЛField;
            }
            set
            {
                this.регИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес МестоДеятельностьИНБОЮЛ
        {
            get
            {
                return this.местоДеятельностьИНБОЮЛField;
            }
            set
            {
                this.местоДеятельностьИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнакОргФормаИНБОЮЛ
        {
            get
            {
                return this.признакОргФормаИНБОЮЛField;
            }
            set
            {
                this.признакОргФормаИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Учредитель", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияИНБОЮЛУчредитель[] Учредитель
        {
            get
            {
                return this.учредительField;
            }
            set
            {
                this.учредительField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СведенияИНБОЮЛУчредитель
    {

        private СведенияИНБОЮЛУчредительНаимУчредитель наимУчредительField;

        private Адрес адрУчредительField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияИНБОЮЛУчредительНаимУчредитель НаимУчредитель
        {
            get
            {
                return this.наимУчредительField;
            }
            set
            {
                this.наимУчредительField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес АдрУчредитель
        {
            get
            {
                return this.адрУчредительField;
            }
            set
            {
                this.адрУчредительField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СведенияИНБОЮЛУчредительНаимУчредитель
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФизЛицо", typeof(ФИО), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ЮрЛицо", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class МестоРождения
    {

        private string кодОКСМField;

        private string странаНаименованиеField;

        private string кодСубъектаПоОКАТОField;

        private string районField;

        private string пунктField;

        private string местоРождТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодОКСМ
        {
            get
            {
                return this.кодОКСМField;
            }
            set
            {
                this.кодОКСМField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СтранаНаименование
        {
            get
            {
                return this.странаНаименованиеField;
            }
            set
            {
                this.странаНаименованиеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодСубъектаПоОКАТО
        {
            get
            {
                return this.кодСубъектаПоОКАТОField;
            }
            set
            {
                this.кодСубъектаПоОКАТОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Пункт
        {
            get
            {
                return this.пунктField;
            }
            set
            {
                this.пунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string МестоРождТекст
        {
            get
            {
                return this.местоРождТекстField;
            }
            set
            {
                this.местоРождТекстField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class МигрКарт
    {

        private string кодМигрКартField;

        private string серияМигрКартField;

        private string номМигрКартField;

        private string датНачПребField;

        private string датОкончПребField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодМигрКарт
        {
            get
            {
                return this.кодМигрКартField;
            }
            set
            {
                this.кодМигрКартField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СерияМигрКарт
        {
            get
            {
                return this.серияМигрКартField;
            }
            set
            {
                this.серияМигрКартField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомМигрКарт
        {
            get
            {
                return this.номМигрКартField;
            }
            set
            {
                this.номМигрКартField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатНачПреб
        {
            get
            {
                return this.датНачПребField;
            }
            set
            {
                this.датНачПребField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатОкончПреб
        {
            get
            {
                return this.датОкончПребField;
            }
            set
            {
                this.датОкончПребField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ДокПодтв
    {

        private string видДокКодField;

        private string видДокНаименованиеField;

        private string иноеНаименованиеДокField;

        private string серияДокПребField;

        private string номДокПребField;

        private string начПравПребField;

        private string окончПравПребField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВидДокКод
        {
            get
            {
                return this.видДокКодField;
            }
            set
            {
                this.видДокКодField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВидДокНаименование
        {
            get
            {
                return this.видДокНаименованиеField;
            }
            set
            {
                this.видДокНаименованиеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИноеНаименованиеДок
        {
            get
            {
                return this.иноеНаименованиеДокField;
            }
            set
            {
                this.иноеНаименованиеДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СерияДокПреб
        {
            get
            {
                return this.серияДокПребField;
            }
            set
            {
                this.серияДокПребField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомДокПреб
        {
            get
            {
                return this.номДокПребField;
            }
            set
            {
                this.номДокПребField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НачПравПреб
        {
            get
            {
                return this.начПравПребField;
            }
            set
            {
                this.начПравПребField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОкончПравПреб
        {
            get
            {
                return this.окончПравПребField;
            }
            set
            {
                this.окончПравПребField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ДокУдост
    {

        private string видДокКодField;

        private string видДокНаименованиеField;

        private string иноеНаименованиеДокField;

        private string серияДокField;

        private string номДокField;

        private string датВыдачиДокField;

        private string кемВыданДокField;

        private string кодПодрField;

        private string начПравПребField;

        private string окончПравПребField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВидДокКод
        {
            get
            {
                return this.видДокКодField;
            }
            set
            {
                this.видДокКодField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВидДокНаименование
        {
            get
            {
                return this.видДокНаименованиеField;
            }
            set
            {
                this.видДокНаименованиеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИноеНаименованиеДок
        {
            get
            {
                return this.иноеНаименованиеДокField;
            }
            set
            {
                this.иноеНаименованиеДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СерияДок
        {
            get
            {
                return this.серияДокField;
            }
            set
            {
                this.серияДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомДок
        {
            get
            {
                return this.номДокField;
            }
            set
            {
                this.номДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатВыдачиДок
        {
            get
            {
                return this.датВыдачиДокField;
            }
            set
            {
                this.датВыдачиДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КемВыданДок
        {
            get
            {
                return this.кемВыданДокField;
            }
            set
            {
                this.кемВыданДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодПодр
        {
            get
            {
                return this.кодПодрField;
            }
            set
            {
                this.кодПодрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НачПравПреб
        {
            get
            {
                return this.начПравПребField;
            }
            set
            {
                this.начПравПребField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОкончПравПреб
        {
            get
            {
                return this.окончПравПребField;
            }
            set
            {
                this.окончПравПребField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СведенияФЛИП
    {

        private ФИО фИОФЛИПField;

        private string иННФЛИПField;

        private string сНИЛСФЛField;

        private string полисНомерField;

        private string[] телефонНомерField;

        private string оГРНИПField;

        private string датаРегИПField;

        private string типФЛЧастнаяПрактикаField;

        private string регнНомерField;

        private Адрес адрРегИПField;

        private string докУдЛичнField;

        private ДокУдост сведДокУдЛичнField;

        private ДокПодтв сведДокПребField;

        private МигрКарт сведМигрКартField;

        private string датаРожденияField;

        private МестоРождения местоРождField;

        private string кодОКСМField;

        private string странаНаименованиеField;

        private string признакПубЛицоField;

        private Адрес адрРегField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФИО ФИОФЛИП
        {
            get
            {
                return this.фИОФЛИПField;
            }
            set
            {
                this.фИОФЛИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИННФЛИП
        {
            get
            {
                return this.иННФЛИПField;
            }
            set
            {
                this.иННФЛИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СНИЛСФЛ
        {
            get
            {
                return this.сНИЛСФЛField;
            }
            set
            {
                this.сНИЛСФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПолисНомер
        {
            get
            {
                return this.полисНомерField;
            }
            set
            {
                this.полисНомерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТелефонНомер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ТелефонНомер
        {
            get
            {
                return this.телефонНомерField;
            }
            set
            {
                this.телефонНомерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОГРНИП
        {
            get
            {
                return this.оГРНИПField;
            }
            set
            {
                this.оГРНИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаРегИП
        {
            get
            {
                return this.датаРегИПField;
            }
            set
            {
                this.датаРегИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТипФЛЧастнаяПрактика
        {
            get
            {
                return this.типФЛЧастнаяПрактикаField;
            }
            set
            {
                this.типФЛЧастнаяПрактикаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string РегнНомер
        {
            get
            {
                return this.регнНомерField;
            }
            set
            {
                this.регнНомерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес АдрРегИП
        {
            get
            {
                return this.адрРегИПField;
            }
            set
            {
                this.адрРегИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДокУдЛичн
        {
            get
            {
                return this.докУдЛичнField;
            }
            set
            {
                this.докУдЛичнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ДокУдост СведДокУдЛичн
        {
            get
            {
                return this.сведДокУдЛичнField;
            }
            set
            {
                this.сведДокУдЛичнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ДокПодтв СведДокПреб
        {
            get
            {
                return this.сведДокПребField;
            }
            set
            {
                this.сведДокПребField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МигрКарт СведМигрКарт
        {
            get
            {
                return this.сведМигрКартField;
            }
            set
            {
                this.сведМигрКартField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаРождения
        {
            get
            {
                return this.датаРожденияField;
            }
            set
            {
                this.датаРожденияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МестоРождения МестоРожд
        {
            get
            {
                return this.местоРождField;
            }
            set
            {
                this.местоРождField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодОКСМ
        {
            get
            {
                return this.кодОКСМField;
            }
            set
            {
                this.кодОКСМField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СтранаНаименование
        {
            get
            {
                return this.странаНаименованиеField;
            }
            set
            {
                this.странаНаименованиеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнакПубЛицо
        {
            get
            {
                return this.признакПубЛицоField;
            }
            set
            {
                this.признакПубЛицоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес АдрРег
        {
            get
            {
                return this.адрРегField;
            }
            set
            {
                this.адрРегField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СведенияЕИО
    {

        private string типЕИОField;

        private string признЕИОField;

        private СведенияЮЛ юЛЕИОField;

        private СведенияФЛИП фЛЕИОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТипЕИО
        {
            get
            {
                return this.типЕИОField;
            }
            set
            {
                this.типЕИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнЕИО
        {
            get
            {
                return this.признЕИОField;
            }
            set
            {
                this.признЕИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияЮЛ ЮЛЕИО
        {
            get
            {
                return this.юЛЕИОField;
            }
            set
            {
                this.юЛЕИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияФЛИП ФЛЕИО
        {
            get
            {
                return this.фЛЕИОField;
            }
            set
            {
                this.фЛЕИОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СведенияЮЛ
    {

        private string наимЮЛField;

        private string признакФлЮЛField;

        private string иННЮЛField;

        private string кППЮЛField;

        private string оГРНЮЛField;

        private Адрес адрРегЮЛField;

        private string датаРегЮЛField;

        private string датаАккредитацииField;

        private Адрес адрЮЛField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимЮЛ
        {
            get
            {
                return this.наимЮЛField;
            }
            set
            {
                this.наимЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнакФлЮЛ
        {
            get
            {
                return this.признакФлЮЛField;
            }
            set
            {
                this.признакФлЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КППЮЛ
        {
            get
            {
                return this.кППЮЛField;
            }
            set
            {
                this.кППЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОГРНЮЛ
        {
            get
            {
                return this.оГРНЮЛField;
            }
            set
            {
                this.оГРНЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес АдрРегЮЛ
        {
            get
            {
                return this.адрРегЮЛField;
            }
            set
            {
                this.адрРегЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаРегЮЛ
        {
            get
            {
                return this.датаРегЮЛField;
            }
            set
            {
                this.датаРегЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаАккредитации
        {
            get
            {
                return this.датаАккредитацииField;
            }
            set
            {
                this.датаАккредитацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Адрес АдрЮЛ
        {
            get
            {
                return this.адрЮЛField;
            }
            set
            {
                this.адрЮЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Документ
    {

        private string кодДокField;

        private string наимДокField;

        private string иноеНаимДокField;

        private string датаДокField;

        private string номДокField;

        private string содДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодДок
        {
            get
            {
                return this.кодДокField;
            }
            set
            {
                this.кодДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимДок
        {
            get
            {
                return this.наимДокField;
            }
            set
            {
                this.наимДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИноеНаимДок
        {
            get
            {
                return this.иноеНаимДокField;
            }
            set
            {
                this.иноеНаимДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаДок
        {
            get
            {
                return this.датаДокField;
            }
            set
            {
                this.датаДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомДок
        {
            get
            {
                return this.номДокField;
            }
            set
            {
                this.номДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СодДок
        {
            get
            {
                return this.содДокField;
            }
            set
            {
                this.содДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ДрагМеталл
    {

        private string кодДрагМеталлField;

        private string наимДрагМеталлField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодДрагМеталл
        {
            get
            {
                return this.кодДрагМеталлField;
            }
            set
            {
                this.кодДрагМеталлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимДрагМеталл
        {
            get
            {
                return this.наимДрагМеталлField;
            }
            set
            {
                this.наимДрагМеталлField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Филиал
    {

        private string регНомКОField;

        private string номФлField;

        private string бИКФлField;

        private string оКАТОФлField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string РегНомКО
        {
            get
            {
                return this.регНомКОField;
            }
            set
            {
                this.регНомКОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомФл
        {
            get
            {
                return this.номФлField;
            }
            set
            {
                this.номФлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БИКФл
        {
            get
            {
                return this.бИКФлField;
            }
            set
            {
                this.бИКФлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОКАТОФл
        {
            get
            {
                return this.оКАТОФлField;
            }
            set
            {
                this.оКАТОФлField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Банк
    {

        private string регНомКОField;

        private string бИККОField;

        private string номФлПередающийField;

        private string оКАТОКОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string РегНомКО
        {
            get
            {
                return this.регНомКОField;
            }
            set
            {
                this.регНомКОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БИККО
        {
            get
            {
                return this.бИККОField;
            }
            set
            {
                this.бИККОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомФлПередающий
        {
            get
            {
                return this.номФлПередающийField;
            }
            set
            {
                this.номФлПередающийField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОКАТОКО
        {
            get
            {
                return this.оКАТОКОField;
            }
            set
            {
                this.оКАТОКОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧасть
    {

        private Банк инфБанкField;

        private СообщОперКОИнформЧастьСведКО[] сведКОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Банк ИнфБанк
        {
            get
            {
                return this.инфБанкField;
            }
            set
            {
                this.инфБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведКО", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКО[] СведКО
        {
            get
            {
                return this.сведКОField;
            }
            set
            {
                this.сведКОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКО
    {

        private string признакПредставСведField;

        private Филиал инфФилиалField;

        private СообщОперКОИнформЧастьСведКООперация[] операцияField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнакПредставСвед
        {
            get
            {
                return this.признакПредставСведField;
            }
            set
            {
                this.признакПредставСведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Филиал ИнфФилиал
        {
            get
            {
                return this.инфФилиалField;
            }
            set
            {
                this.инфФилиалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Операция", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперация[] Операция
        {
            get
            {
                return this.операцияField;
            }
            set
            {
                this.операцияField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперация
    {

        private string номерЗаписиField;

        private string типЗаписиField;

        private string номерОперацияField;

        private string[] признФТрField;

        private string датаОперацииField;

        private string датаВыявленияField;

        private string кодПризнОперацииField;

        private string признакОперацияЭСПField;

        private string наимПлатежнаяСистема1Field;

        private string наимПлатежнаяСистема2Field;

        private string времяТранзакцияЭСПField;

        private string кодОперацииField;

        private string[] допКодОперацииField;

        private string[] признНеобОперацииField;

        private string кодВалField;

        private string сумОперацииField;

        private string сумРубField;

        private string кодВалКонверсияField;

        private string сумКонверсияField;

        private ДрагМеталл[] сведДрагМеталлField;

        private Документ[] основаниеОпField;

        private string назначениеПлатежаField;

        private string характерОпField;

        private СообщОперКОИнформЧастьСведКООперацияУчастникОп[] участникОпField;

        private СообщОперКОИнформЧастьСведКООперацияСведенияПереводыДС сведенияПереводыДСField;

        private СообщОперКОИнформЧастьСведКООперацияСведенияВнесениеПолучениеНалДС сведенияВнесениеПолучениеНалДСField;

        private СообщОперКОИнформЧастьСведКООперацияСведенияКартаИнБанк сведенияКартаИнБанкField;

        private string комментField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерЗаписи
        {
            get
            {
                return this.номерЗаписиField;
            }
            set
            {
                this.номерЗаписиField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТипЗаписи
        {
            get
            {
                return this.типЗаписиField;
            }
            set
            {
                this.типЗаписиField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерОперация
        {
            get
            {
                return this.номерОперацияField;
            }
            set
            {
                this.номерОперацияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПризнФТр", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ПризнФТр
        {
            get
            {
                return this.признФТрField;
            }
            set
            {
                this.признФТрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаОперации
        {
            get
            {
                return this.датаОперацииField;
            }
            set
            {
                this.датаОперацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ДатаВыявления
        {
            get
            {
                return this.датаВыявленияField;
            }
            set
            {
                this.датаВыявленияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодПризнОперации
        {
            get
            {
                return this.кодПризнОперацииField;
            }
            set
            {
                this.кодПризнОперацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнакОперацияЭСП
        {
            get
            {
                return this.признакОперацияЭСПField;
            }
            set
            {
                this.признакОперацияЭСПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимПлатежнаяСистема1
        {
            get
            {
                return this.наимПлатежнаяСистема1Field;
            }
            set
            {
                this.наимПлатежнаяСистема1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимПлатежнаяСистема2
        {
            get
            {
                return this.наимПлатежнаяСистема2Field;
            }
            set
            {
                this.наимПлатежнаяСистема2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВремяТранзакцияЭСП
        {
            get
            {
                return this.времяТранзакцияЭСПField;
            }
            set
            {
                this.времяТранзакцияЭСПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодОперации
        {
            get
            {
                return this.кодОперацииField;
            }
            set
            {
                this.кодОперацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДопКодОперации", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ДопКодОперации
        {
            get
            {
                return this.допКодОперацииField;
            }
            set
            {
                this.допКодОперацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПризнНеобОперации", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ПризнНеобОперации
        {
            get
            {
                return this.признНеобОперацииField;
            }
            set
            {
                this.признНеобОперацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодВал
        {
            get
            {
                return this.кодВалField;
            }
            set
            {
                this.кодВалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СумОперации
        {
            get
            {
                return this.сумОперацииField;
            }
            set
            {
                this.сумОперацииField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СумРуб
        {
            get
            {
                return this.сумРубField;
            }
            set
            {
                this.сумРубField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодВалКонверсия
        {
            get
            {
                return this.кодВалКонверсияField;
            }
            set
            {
                this.кодВалКонверсияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СумКонверсия
        {
            get
            {
                return this.сумКонверсияField;
            }
            set
            {
                this.сумКонверсияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведДрагМеталл", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ДрагМеталл[] СведДрагМеталл
        {
            get
            {
                return this.сведДрагМеталлField;
            }
            set
            {
                this.сведДрагМеталлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснованиеОп", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Документ[] ОснованиеОп
        {
            get
            {
                return this.основаниеОпField;
            }
            set
            {
                this.основаниеОпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НазначениеПлатежа
        {
            get
            {
                return this.назначениеПлатежаField;
            }
            set
            {
                this.назначениеПлатежаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ХарактерОп
        {
            get
            {
                return this.характерОпField;
            }
            set
            {
                this.характерОпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("УчастникОп", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияУчастникОп[] УчастникОп
        {
            get
            {
                return this.участникОпField;
            }
            set
            {
                this.участникОпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияСведенияПереводыДС СведенияПереводыДС
        {
            get
            {
                return this.сведенияПереводыДСField;
            }
            set
            {
                this.сведенияПереводыДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияСведенияВнесениеПолучениеНалДС СведенияВнесениеПолучениеНалДС
        {
            get
            {
                return this.сведенияВнесениеПолучениеНалДСField;
            }
            set
            {
                this.сведенияВнесениеПолучениеНалДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияСведенияКартаИнБанк СведенияКартаИнБанк
        {
            get
            {
                return this.сведенияКартаИнБанкField;
            }
            set
            {
                this.сведенияКартаИнБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Коммент
        {
            get
            {
                return this.комментField;
            }
            set
            {
                this.комментField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияУчастникОп
    {

        private string статусУчастникаField;

        private string типУчастникаField;

        private string признУчастникаField;

        private string признКлиентField;

        private string кодЮЛФЛField;

        private СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникЮЛ участникЮЛField;

        private СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникФЛИП участникФЛИПField;

        private СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникИНБОЮЛ участникИНБОЮЛField;

        private string комментУчастникField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СтатусУчастника
        {
            get
            {
                return this.статусУчастникаField;
            }
            set
            {
                this.статусУчастникаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТипУчастника
        {
            get
            {
                return this.типУчастникаField;
            }
            set
            {
                this.типУчастникаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнУчастника
        {
            get
            {
                return this.признУчастникаField;
            }
            set
            {
                this.признУчастникаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнКлиент
        {
            get
            {
                return this.признКлиентField;
            }
            set
            {
                this.признКлиентField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодЮЛФЛ
        {
            get
            {
                return this.кодЮЛФЛField;
            }
            set
            {
                this.кодЮЛФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникЮЛ УчастникЮЛ
        {
            get
            {
                return this.участникЮЛField;
            }
            set
            {
                this.участникЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникФЛИП УчастникФЛИП
        {
            get
            {
                return this.участникФЛИПField;
            }
            set
            {
                this.участникФЛИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникИНБОЮЛ УчастникИНБОЮЛ
        {
            get
            {
                return this.участникИНБОЮЛField;
            }
            set
            {
                this.участникИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КомментУчастник
        {
            get
            {
                return this.комментУчастникField;
            }
            set
            {
                this.комментУчастникField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникЮЛ
    {

        private СведенияЮЛ сведЮЛField;

        private СведенияЕИО[] сведЕИОField;

        private СведенияЮЛ новСведЮЛField;

        private СведенияЕИО[] новСведЕИОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияЮЛ СведЮЛ
        {
            get
            {
                return this.сведЮЛField;
            }
            set
            {
                this.сведЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведЕИО", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияЕИО[] СведЕИО
        {
            get
            {
                return this.сведЕИОField;
            }
            set
            {
                this.сведЕИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияЮЛ НовСведЮЛ
        {
            get
            {
                return this.новСведЮЛField;
            }
            set
            {
                this.новСведЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НовСведЕИО", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияЕИО[] НовСведЕИО
        {
            get
            {
                return this.новСведЕИОField;
            }
            set
            {
                this.новСведЕИОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникФЛИП
    {

        private string идентификацияФЛField;

        private СведенияФЛИП сведФЛИПField;

        private СведенияФЛИП новСведФЛИПField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ИдентификацияФЛ
        {
            get
            {
                return this.идентификацияФЛField;
            }
            set
            {
                this.идентификацияФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияФЛИП СведФЛИП
        {
            get
            {
                return this.сведФЛИПField;
            }
            set
            {
                this.сведФЛИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияФЛИП НовСведФЛИП
        {
            get
            {
                return this.новСведФЛИПField;
            }
            set
            {
                this.новСведФЛИПField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияУчастникОпУчастникИНБОЮЛ
    {

        private СведенияИНБОЮЛ сведИНБОЮЛField;

        private СведенияИНБОЮЛ новСведИНБОЮЛField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияИНБОЮЛ СведИНБОЮЛ
        {
            get
            {
                return this.сведИНБОЮЛField;
            }
            set
            {
                this.сведИНБОЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СведенияИНБОЮЛ НовСведИНБОЮЛ
        {
            get
            {
                return this.новСведИНБОЮЛField;
            }
            set
            {
                this.новСведИНБОЮЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияСведенияПереводыДС
    {

        private string видПереводДСField;

        private string кодТерИнГосField;

        private string типОператорДСField;

        private string номерСчетПлательщикField;

        private string[] идентЭСППлательщикField;

        private БанкПлательщикПолучатель сведБанкПлательщикField;

        private БанкПлательщикПолучатель сведБанкПолучательField;

        private string счетБанкПлательщикField;

        private string счетБанкПолучательField;

        private string номерСчетПолучательField;

        private string[] идентЭСППолучателяField;

        private МестоПриемаВыдача сведПриемНалДСField;

        private string статусПереводField;

        private МестоПриемаВыдача сведВыдачаНалДСField;

        private МестоПриемаВыдача сведАвторизацияЭСПField;

        private string адресIPField;

        private string адресMACField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ВидПереводДС
        {
            get
            {
                return this.видПереводДСField;
            }
            set
            {
                this.видПереводДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодТерИнГос
        {
            get
            {
                return this.кодТерИнГосField;
            }
            set
            {
                this.кодТерИнГосField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ТипОператорДС
        {
            get
            {
                return this.типОператорДСField;
            }
            set
            {
                this.типОператорДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерСчетПлательщик
        {
            get
            {
                return this.номерСчетПлательщикField;
            }
            set
            {
                this.номерСчетПлательщикField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИдентЭСППлательщик", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ИдентЭСППлательщик
        {
            get
            {
                return this.идентЭСППлательщикField;
            }
            set
            {
                this.идентЭСППлательщикField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public БанкПлательщикПолучатель СведБанкПлательщик
        {
            get
            {
                return this.сведБанкПлательщикField;
            }
            set
            {
                this.сведБанкПлательщикField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public БанкПлательщикПолучатель СведБанкПолучатель
        {
            get
            {
                return this.сведБанкПолучательField;
            }
            set
            {
                this.сведБанкПолучательField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СчетБанкПлательщик
        {
            get
            {
                return this.счетБанкПлательщикField;
            }
            set
            {
                this.счетБанкПлательщикField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СчетБанкПолучатель
        {
            get
            {
                return this.счетБанкПолучательField;
            }
            set
            {
                this.счетБанкПолучательField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерСчетПолучатель
        {
            get
            {
                return this.номерСчетПолучательField;
            }
            set
            {
                this.номерСчетПолучательField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИдентЭСППолучателя", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ИдентЭСППолучателя
        {
            get
            {
                return this.идентЭСППолучателяField;
            }
            set
            {
                this.идентЭСППолучателяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МестоПриемаВыдача СведПриемНалДС
        {
            get
            {
                return this.сведПриемНалДСField;
            }
            set
            {
                this.сведПриемНалДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СтатусПеревод
        {
            get
            {
                return this.статусПереводField;
            }
            set
            {
                this.статусПереводField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МестоПриемаВыдача СведВыдачаНалДС
        {
            get
            {
                return this.сведВыдачаНалДСField;
            }
            set
            {
                this.сведВыдачаНалДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МестоПриемаВыдача СведАвторизацияЭСП
        {
            get
            {
                return this.сведАвторизацияЭСПField;
            }
            set
            {
                this.сведАвторизацияЭСПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string АдресIP
        {
            get
            {
                return this.адресIPField;
            }
            set
            {
                this.адресIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string АдресMAC
        {
            get
            {
                return this.адресMACField;
            }
            set
            {
                this.адресMACField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияСведенияВнесениеПолучениеНалДС
    {

        private string кодХарактерОпField;

        private string номерСчетКлиентField;

        private string номерКартаField;

        private МестоПриемаВыдача сведПриемВыдачаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодХарактерОп
        {
            get
            {
                return this.кодХарактерОпField;
            }
            set
            {
                this.кодХарактерОпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерСчетКлиент
        {
            get
            {
                return this.номерСчетКлиентField;
            }
            set
            {
                this.номерСчетКлиентField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерКарта
        {
            get
            {
                return this.номерКартаField;
            }
            set
            {
                this.номерКартаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МестоПриемаВыдача СведПриемВыдача
        {
            get
            {
                return this.сведПриемВыдачаField;
            }
            set
            {
                this.сведПриемВыдачаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СообщОперКОИнформЧастьСведКООперацияСведенияКартаИнБанк
    {

        private string кодТерИнБанкField;

        private МестоПриемаВыдача сведМестоОперацияField;

        private string номерКартаField;

        private string сведДержательКартыField;

        private string признакСотрудникField;

        private string наимИнБанкField;

        private string сВИФТИнБанкField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодТерИнБанк
        {
            get
            {
                return this.кодТерИнБанкField;
            }
            set
            {
                this.кодТерИнБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public МестоПриемаВыдача СведМестоОперация
        {
            get
            {
                return this.сведМестоОперацияField;
            }
            set
            {
                this.сведМестоОперацияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НомерКарта
        {
            get
            {
                return this.номерКартаField;
            }
            set
            {
                this.номерКартаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СведДержательКарты
        {
            get
            {
                return this.сведДержательКартыField;
            }
            set
            {
                this.сведДержательКартыField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ПризнакСотрудник
        {
            get
            {
                return this.признакСотрудникField;
            }
            set
            {
                this.признакСотрудникField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string НаимИнБанк
        {
            get
            {
                return this.наимИнБанкField;
            }
            set
            {
                this.наимИнБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string СВИФТИнБанк
        {
            get
            {
                return this.сВИФТИнБанкField;
            }
            set
            {
                this.сВИФТИнБанкField = value;
            }
        }
    }
}
